version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pnpm
      - pnpm install
  pre_build:
    commands:
      - pnpm run test
  build:
    commands:
      - npx cdk synth

artifacts:
  files:
    - "**/*"